### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wnpllrzodiac** [tjliupeng/nginx-build-windows#1]
when build openssl meet error as follows:

`Perl v5.10.0 required--this is only v5.8.8, stopped at Configure line 12`

I use msys 1.0, how can I update perl tool to new version?
I try 
https://sourceforge.net/projects/perl-mingw/files/5.24.0/

But new error come up
```
This perl implementation doesn't produce Windows like paths (with backward
slash directory separators).  Please use an implementation that matches your
building platform.

This Perl version: 5.24.0 for MSWin32-x86-multi-thread-64int
```

**Comment by tjliupeng** [comment]
Sorry for the late reply. Although I don't work on this in the recent several years, I googled this issue and found the similar issue here https://github.com/openssl/openssl/issues/9048. If it is true, the issue should be related to the Perl version.

**Comment by wnpllrzodiac** [comment]
thank you for your reply.
I fix the build problem by install win32 perl environment.
No good solution to use msys1.0+mingw old perl version.
